# Generated by Django 5.1.3 on 2025-05-22 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.FileField(help_text='Upload SVG icon file', upload_to='category_icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
