# Generated by Django 5.1.3 on 2025-05-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productsubcategory_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='level',
            field=models.IntegerField(default=0, help_text='0 for main category, 1 for subcategory, 2 for sub-subcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.productcategory'),
        ),
        migrations.DeleteModel(
            name='ProductSubCategory',
        ),
    ]
